### ISSUE TITLE
Enabling API key handling (MissingKeyMapError)

### ISSUE THREAD

**Issue by bluenote10** [vgm64/gmplot#16] opened 2016-06-23 13:22 UTC
It looks like Google Maps no longer allows key-less API access [as of yesterday June 22th](http://stackoverflow.com/questions/37991340/error-google-maps-api-error-missingkeymaperror). This will probably require to enable passing an API key to gmplot. Currently using gmplot fails with `MissingKeyMapError`.

**Comment by santoshphilip** [comment] 2016-06-23 20:09
a quick workaround until it is fixed:
(You need to install BeautifulSoup - `pip install beautifulsoup4`)

    import gmplot

    gmap = gmplot.GoogleMapPlotter(37.428, -122.145, 16)
    gmap.draw("mymap.html")    
    # "mymap.html" will NOT open
    
    from bs4 import BeautifulSoup
    
    def insertapikey(fname, apikey):
        """put the google api key in a html file"""
        def putkey(htmltxt, apikey, apistring=None):
            """put the apikey in the htmltxt and return soup"""
            if not apistring:
                apistring = "https://maps.googleapis.com/maps/api/js?key=%s&callback=initMap"
            soup = BeautifulSoup(htmltxt, 'html.parser')
            body = soup.body
            src = apistring % (apikey, )
            tscript = soup.new_tag("script", src=src, async="defer")
            body.insert(-1, tscript)
            return soup
        htmltxt = open(fname, 'r').read()
        soup = putkey(htmltxt, apikey)
        newtxt = soup.prettify()
        open(fname, 'w').write(newtxt)
    
    insertapikey("mymap.html", apikey)
    # "mymap.html" will open

I wrote this because I needed it right now :-)

**Comment by fuzunspm** [comment] 2017-05-30 14:15
@santoshphilip could you please explain more about htmltxt and apikey? i couldn't manage to do it

**Comment by santoshphilip** [comment] 2017-05-30 14:39
I have not used it since I wrote it - so my recollection of this is a little fuzzy.

- The API key has to be in the html for the page to open.
- gmplot makes the page without the API key in the html
- The code above opens the html file and inserts the API key in the right place in the html
- The new html file (the old file is overwritten) will open.

You need to get the API key from google (the google maps page may guide on this)

Having said this, all of the above is from almost a year back. I have not tested the code to see if it still works. Things may have changed since then.

Good luck

**Comment by joemcmanus** [comment] 2017-06-26 22:10
Here is my fix for using this in flask. All you need to do is add &key= to the already existing visualization line. 

After you create the map run this snippet of code that uses replace() to add in the API key. 
#gmap does not have a apikey function, so lets substitute it. 
        tempHolder=''
        oldLine='<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=visualization&sensor=true_or_false"></script>'
        newLine='<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=visualization&sensor=true_or_false&key=yourKeyHere"></script>'
        with open('static/map.html') as fh:
                for line in fh:
                        tempHolder += line.replace(oldLine,newLine)
        fh.close
        fh=open('static/map.html', 'w')
        fh.write(tempHolder)
        fh.close

Hope that helps.

**Comment by Leocorp** [comment] 2017-09-11 10:22
Here is an update to @santoshphilip 's code:

def insertapikey(fname, apikey):
    """put the google api key in a html file"""
    print('\n###############################')
    print('\n Beginning Key Insertion ...')

    def putkey(htmltxt, apikey, apistring=None):
        """put the apikey in the htmltxt and return soup"""
        if not apistring:
            apistring = "https://maps.googleapis.com/maps/api/js?key=%s&callback=initialize&libraries=visualization&sensor=true_or_false"
        soup = BeautifulSoup(htmltxt, 'html.parser')
        soup.script.decompose() #remove the existing script tag
        body = soup.body
        src = apistring % (apikey,)
        tscript = soup.new_tag("script", src=src, async="defer")
        body.insert(-1, tscript)
        return soup

    htmltxt = open(fname, 'r').read()
    soup = putkey(htmltxt, apikey)
    newtxt = soup.prettify()
    open(fname, 'w').write(newtxt)
    print('\nKey Insertion Completed!!')

if __name__ == '__main__':
    insertapikey("map.html", api_key)

NB: 

- The **initMap()** function has been changed to **initialize()**

- And also removes the previous 'script' inserted by the gmplot map generation

**Comment by frmsaul** [comment] 2017-10-24 23:49
In case anybody, encounters the same problem, here is the workaround i've been using for Jupyter / IPython. 

```python 
from IPython.display import IFrame

def jupyter_display(gmplot_filename, google_api_key):
    """Hack to display a gmplot map in Jupyter"""
    with open(gmplot_filename, "r+b") as f:
        f_string = f.read()
        url_pattern = "https://maps.googleapis.com/maps/api/js?libraries=visualization&sensor=true_or_false"
        f_string = f_string.replace(url_pattern, url_pattern + "&key=%s" % google_api_key)
        f.write(f_string)
    return IFrame(gmplot_filename, width=990, height=500)
```

**Comment by vgm64** [comment] 2017-10-25 05:10
Merged api key branch. Reopen if the issue is still present. fwiw, I've been using api-less plotting since this ticket was opened without issue. I understand the notebooks may be a bit different.

**Closed by vgm64** 2017-10-25 05:10 UTC
